const SHOWS = {
    LOAD: 'SHOWS_LOAD',
    LOAD_SUCCESS: 'SHOWS_LOAD_SUCCESS',
    LOAD_FAIL: 'SHOWS_LOAD_FAIL',
    ADD_SHOW_TO_TABLE: 'ADD_SHOW_TO_TABLE',
    REMOVE_SHOW_FROM_TABLE: 'REMOVE_SHOW_FROM_TABLE',
};

export {SHOWS};